"""empty message

Revision ID: 855fe84cff88
Revises: 
Create Date: 2022-10-26 01:38:04.104031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855fe84cff88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_searched', sa.String(), nullable=True),
    sa.Column('dt_stamp', sa.Date(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'weather', ['station'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather', type_='unique')
    op.drop_table('search_results')
    # ### end Alembic commands ###
